"""add_equipment_type_to_atribuicao

Revision ID: 9d03e81c6107
Revises: f8d76b387ebd
Create Date: 2026-04-07 09:04:24.484194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d03e81c6107'
down_revision: Union[str, Sequence[str], None] = 'f8d76b387ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atribuicao', sa.Column('equipment_type', sa.String(length=20), nullable=False, server_default='coletor'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('atribuicao', 'equipment_type')
    # ### end Alembic commands ###
