"""cria tabela de usuarios

Revision ID: db7e0cf0c891
Revises: 6cda6d748b9a
Create Date: 2026-03-30 14:46:17.000755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7e0cf0c891'
down_revision: Union[str, Sequence[str], None] = '6cda6d748b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colaborador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('turno', sa.Integer(), nullable=False),
    sa.Column('filial', sa.String(length=50), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colaborador_id'), 'colaborador', ['id'], unique=False)
    op.create_index(op.f('ix_colaborador_matricula'), 'colaborador', ['matricula'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_level', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['matricula'], ['colaborador.matricula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_matricula'), 'users', ['matricula'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_matricula'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_colaborador_matricula'), table_name='colaborador')
    op.drop_index(op.f('ix_colaborador_id'), table_name='colaborador')
    op.drop_table('colaborador')
    # ### end Alembic commands ###
