"""add_session_tracking

Revision ID: f8d76b387ebd
Revises: 77b03eea0f70
Create Date: 2026-04-02 14:07:23.171502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d76b387ebd'
down_revision: Union[str, Sequence[str], None] = '77b03eea0f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('atribuicao_colaborador_id_fkey'), 'atribuicao', type_='foreignkey')
    op.drop_constraint(op.f('atribuicao_coletor_id_fkey'), 'atribuicao', type_='foreignkey')
    op.drop_constraint(op.f('atribuicao_user_id_fkey'), 'atribuicao', type_='foreignkey')
    op.add_column('users', sa.Column('last_activity', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('session_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_id')
    op.drop_column('users', 'last_activity')
    op.create_foreign_key(op.f('atribuicao_user_id_fkey'), 'atribuicao', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('atribuicao_coletor_id_fkey'), 'atribuicao', 'coletores', ['coletor_id'], ['id'])
    op.create_foreign_key(op.f('atribuicao_colaborador_id_fkey'), 'atribuicao', 'colaborador', ['colaborador_id'], ['id'])
    # ### end Alembic commands ###
